name: Run tests
on: [push]

jobs:
  build_and_publish:
    name: Publish repo
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ helloworld ]
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v1
        with:
          go-version: 1.19
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Build service
        working-directory: ./cmd/${{ matrix.service }}
        run: make build
      - name: Build docker image
        working-directory: ./cmd/${{ matrix.service }}
        env:
          IN_TRAVIS_CI: yes
        run: make docker
      - name: Publish docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
          TAG="${{ matrix.service }}-latest"
          DOCKERNAME="xtechnology/${{ github.event.repository.name }}:${TAG}"
          docker tag docker.io/library/${{ matrix.service }}:latest ${DOCKERNAME}
          docker push ${DOCKERNAME}
          docker logout
