name: Run tests
on: [push]

jobs:
  build_and_publish:
    name: Publish repo
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ helloworld ]
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v1
        with:
          go-version: 1.19
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: DOcker build
        working-directory: ./cmd/${{ matrix.service }}
        env:
          IN_TRAVIS_CI: yes
        run: make docker
